### ISSUE TITLE
Expose TypeScripts types

### ISSUE THREAD

**Issue by tbassetto** [cisco-ce/jsxapi#11]
It doesn't mean that the project has to be written in TypeScript, an `index.d.ts` file at the root would be a good start.

https://github.com/Microsoft/dts-gen
https://stackoverflow.com/a/47746553
https://stackoverflow.com/a/12695001
http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by myme** [comment]
Closing this as TypeScript port has been merged.
