### ISSUE TITLE
Create browser bundle in dist/

### ISSUE THREAD

**Issue by myme** [cisco-ce/jsxapi#44]
Create a browser-friendly bundle which is part of the release package, suitable for CDNs like [unpkg](https://unpkg.com/). The browser bundle supports only the WebSocket protocol. Include both a regular and a minified version.

**Comment by tbassetto** [comment]
Have you considered [tsdx](https://www.npmjs.com/package/tsdx) now that the TypeScript branch is merged in? It's using rollup under the hood.

**Comment by myme** [comment]
Removed "rollup" from the title of the issue. Whatever works! Should use the `./src/browser.js` entry-point, as the dist makes only sense for browser environments.

**Comment by tbassetto** [comment]
For later reference:
* Spec for the `browser` field: https://github.com/defunctzombie/package-browser-field-spec
* Spec for the `module` field (~`jsnext:main`): https://github.com/rollup/rollup/wiki/pkg.module (a file with `import` / `export` syntax)
* Spec for the `types` field: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
* Spec for the `main` field?: https://docs.npmjs.com/files/package.json#main They say it should be a module ID, but most packages put a **path to a file** in `main`.

Summary-is? https://areknawo.com/whats-what-package-json-cheatsheet/#main

**Comment by tbassetto** [comment]
What a mess: https://2ality.com/2019/10/hybrid-npm-packages.html
