### ISSUE TITLE
Is there a way to turn off ssl validation on web socket?

### ISSUE THREAD

**Issue by rnwolfe** [cisco-ce/jsxapi#61]
I know WebSocket in general supports it, but does `jsxapi` provide a means to do it. 

From what I can tell looking at the code, it doesn't appear to let us disable cert check?

Though, the most straightforward way to add that option is not obvious to me.

**Comment by rnwolfe** [comment]
I'm now taking a look and see this in the code: 

https://github.com/cisco-ce/jsxapi/blob/55f818f301dc90d52aaabd6fb4bb22634bb0eda6/src/index.ts#L25-L33


However, when using the API in an Angular app, I must accept the HTTPS certificate in another tab before connection is established. When running in Electron, it just won't work, as expected.

Shouldn't the above code accomplish this? It makes sense that it is default given the link-local with self-signed certificate is a common means of accessing the API.

**Comment by myme** [comment]
Sorry for not responding sooner. The code you've pasted a link to is the one used in Node.js environments. That WebSocket implementation is provided by the [ws](https://www.npmjs.com/package/ws) NPM module. It does have an option for ignoring invalid/untrusted certificate chains. Afaik that option is just pushed further down as an option to the Node.js builtin `tls` module.

For browsers it's the following:

https://github.com/cisco-ce/jsxapi/blob/55f818f301dc90d52aaabd6fb4bb22634bb0eda6/src/browser.ts#L14-L16

In browser environments we have to use the browser's WebSocket implementation conforming to the [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) interface. That does not have any means of disabling certificate checks and the process is handled entirely by the browser. I do not know of any browsers prompting about new untrusted certificates encountered over WebSockets, so you'd typically have to do what you say: visit a page over HTTPS first.

I don't know what options there are for Electron, but as it's a dual JavaScript engine environment with both Node.js and Chromium V8 or something it might be an option to run it in the Node.js context. Might be that Electron also has ways of adding custom CAs and/or certificates through APIs. I found this though: https://stackoverflow.com/a/46789486

**Comment by myme** [comment]
To answer the bug title: It depends. It is possible and is in fact default behavior for Node.js WebSockets. For browser environments there is no such thing and nothing we can do.

**Comment by rnwolfe** [comment]
Thanks, @myme. For some reason, it completely slipped my mind that this is essentially a browser context and programmatic ignoring of SSL is a general no go. 

You are right in the Electron part, I can check into the main vs renderer threads to see what options are available. 

I appreciate the insight!
